
["Server config for Multiverse mod"]
	#This is the cooldown of the Boundless Blade item in ticks. 
	#Range: > 0
	boundlessBladeCooldown = 500

	["Server config for Multiverse mod".Rifts]
		#This is the minimum height radius of naturally generated rifts. 
		#Range: > 0
		minHeight = 6
		#This is the chance a rift will generate. Increasing it will cause less rifts to generate. Specifically, each rift has a reciprocal of this value chance to generate per chunk. 
		#Range: > 1
		chance = 20
		#This is the maximum height radius of naturally generated rifts. This should be greater or equal to minHeight. 
		#Range: > 0
		maxHeight = 10
		#This is the range that is scanned for existing rifts. 
		#Range: > 0
		range = 128
		#This is the minimum width radius of naturally generated rifts. 
		#Range: > 0
		minWidth = 1
		#This is the chance of a Fabric of Reality dropping whenever a rift opens. 
		#Range: 0.0 ~ 1.0
		fabricChance = 0.05
		#This is the maximum width radius of naturally generated rifts. This should be greater or equal to minWidth. 
		#Range: > 0
		maxWidth = 3

	["Server config for Multiverse mod"."Multiverse dimensions"]
		#This is whether Multiverse dimensions can generate worlds with a ceiling but no floor. Defaulted to false because it is extremely difficult and painful to navigate in these worlds. 
		inverse = false
		#This is the chance that a Multiverse dimension has a random, fixed time. 
		#Range: 0.0 ~ 1.0
		fixedTimeChance = 0.25
		#Each additional biome type has this chance to be in new Multiverse dimensions. 
		#Range: 0.0 ~ 1.0
		biomeTypeChance = 0.025
		#This is the number of Multiverse dimensions that rifts will generate for. 
		#Range: > 1
		max = 25

